DROP TABLE IF EXISTS SALA_PROFESSOR;
drop table if exists professor;
drop table if exists sala;

CREATE TABLE SALA(ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   NUMERO BIGINT);

insert into sala(numero) values(1);
insert into sala(numero) values(2);
insert into sala(numero) values(3);

CREATE TABLE PROFESSOR(ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    SOBRENOME VARCHAR(255),
    CADASTRO BIGINT NOT NULL)

insert into professor (nome, cadastro) values ('teste', 123);
insert into professor (nome, cadastro) values ('teste', 321);

CREATE TABLE SALA_PROFESSOR (
   SALA BIGINT NOT NULL,
   PROFESSOR BIGINT NOT NULL,
  CONSTRAINT fk_sala
  FOREIGN KEY (SALA) REFERENCES SALA (ID),
  CONSTRAINT fk_professor
  FOREIGN KEY (PROFESSOR) REFERENCES PROFESSOR (ID),
  PRIMARY KEY (SALA, PROFESSOR));

insert into SALA_PROFESSOR values (1,1);
insert into SALA_PROFESSOR values (1,2);
insert into SALA_PROFESSOR values (2,1);
insert into SALA_PROFESSOR values (2,2);
select S.ID, S.NUMERO, P.ID, P.NOME from SALA_PROFESSOR SP
INNER JOIN SALA S
ON SP.SALA = S.ID
INNER JOIN PROFESSOR P
ON SP.PROFESSOR = P.ID
WHERE P.ID = 1;

select S.ID, S.NUMERO, P.ID, P.NOME from SALA_PROFESSOR SP
INNER JOIN SALA S
ON SP.SALA = S.ID
INNER JOIN PROFESSOR P
ON SP.PROFESSOR = P.ID
WHERE S.ID = 1;

------

DROP TABLE PROFESSOR_MATERIA;
DROP TABLE AULA_ALUNO;
DROP TABLE AULA;
DROP TABLE ALUNO;
DROP TABLE PROFESSOR;
DROP TABLE SALA;
DROP TABLE MATERIA;

CREATE TABLE SALA(ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   NUMERO BIGINT);

insert into sala(numero) values(1);
insert into sala(numero) values(2);
insert into sala(numero) values(3);

CREATE TABLE MATERIA(ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   NOME VARCHAR(55));

INSERT INTO MATERIA (NOME) VALUES ('MATEMATICA');
INSERT INTO MATERIA (NOME) VALUES ('FISICA');

CREATE TABLE PROFESSOR(ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL);

insert into professor (nome) values ('teste');
insert into professor (nome) values ('teste1');

CREATE TABLE ALUNO(ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL);

INSERT INTO ALUNO (NOME) VALUES ('FRANCISCO');
INSERT INTO ALUNO (NOME) VALUES ('PEDRO');
INSERT INTO ALUNO (NOME) VALUES ('JOÃO');
INSERT INTO ALUNO (NOME) VALUES ('LUIZ');

CREATE TABLE PROFESSOR_MATERIA(
   PROFESSOR BIGINT NOT NULL,
   MATERIA BIGINT NOT NULL,
  CONSTRAINT fk_professor
  FOREIGN KEY (PROFESSOR) REFERENCES PROFESSOR (ID),
  CONSTRAINT fk_materia
  FOREIGN KEY (MATERIA) REFERENCES MATERIA (ID),
  PRIMARY KEY (PROFESSOR, MATERIA));

INSERT INTO PROFESSOR_MATERIA VALUES (1, 2);
INSERT INTO PROFESSOR_MATERIA VALUES (2, 1);

CREATE TABLE AULA (ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
SALA BIGINT NOT NULL,
PROFESSOR BIGINT NOT NULL,
MATERIA BIGINT,
HORARIO DATE,
CONSTRAINT fk_aula_sala_id
  FOREIGN KEY (SALA) REFERENCES SALA(ID),
CONSTRAINT fk_aula_professor_id
  FOREIGN KEY (PROFESSOR) REFERENCES PROFESSOR (ID),
CONSTRAINT fk_aula_materia
  FOREIGN KEY (MATERIA) REFERENCES MATERIA(ID));

CREATE TABLE AULA_ALUNO(
   AULA BIGINT NOT NULL,
   ALUNO BIGINT NOT NULL,
  CONSTRAINT fk_aula
  FOREIGN KEY (AULA) REFERENCES AULA(ID),
  CONSTRAINT fk_aluno
  FOREIGN KEY (ALUNO) REFERENCES ALUNO (ID),
  PRIMARY KEY (AULA, ALUNO));
